### ISSUE TITLE
Defining IssueRepo

### ISSUE THREAD

**Issue by ken5scal** [ossf/allstar#152]
https://github.com/ossf/allstar/pull/80

We are trying to centralize all issues in Org to repo `centralRepo`, but not exactly sure how to setup IssueRepo.
In that case, I am assuming what we define in `allstar.yaml` within `.allstar` repo is the following.

```
optConfig:
  optOutStrategy: true
  disableRepoOverride: true
issueRepo: centralRepo
```

But, I'm not quite sure because it seems none of the issue is appearing in the repo.
