### ISSUE TITLE
Consider not pinging issues on the weekend

### ISSUE THREAD

**Issue by thatch** [ossf/allstar#201]
For example https://github.com/google/makerspace-auth/issues/47 -- it's existed in this state for years, and I get github notifications on my personal devices.  This is not kind to work-life balance, if this is intended for work projects...

**Comment by ghost** [comment]
This would be a nice org + repo config option.
Weekends could be configured sort of like this:
```yaml
optOutDays:
- issue: false
  pr: false
  days:
    - 0
    - 6
  timezone: pst
```
See [Weekday](https://pkg.go.dev/time#Weekday).
Limit the config to opting out three days per week or so.

**Comment by ghost** [comment]
As discussed in today's bi-weekly meeting, it might be nice to take some inspiration from the way Dependabot's config handles skipping days (see relevant Dependabot docs [here](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleday)).

Here is what that might look like in an organization's `allstar.yaml` config:
```yaml
optConfig:
  optOutStrategy: true
  optSchedule:
    timezone: America/Los_Angeles
    actions:
      issue: false
      fix: true
    days:
      - saturday
      - sunday
```

Fix will default to `true`.

It isn't exactly the same, but it is familiar. We could also automatically support the Dependabot configuration by looking at each repo's `.github/dependabot.yml` to find the schedule information there, inverting the days listed to get `skipDays`.

Be sure to limit skipDays to 3 days or so so that it isn't used as a tricky opt-out strategy.
