### ISSUE TITLE
Is it possible to define branch protections and base checks, allowing additional checks to be defined at the repo level?

### ISSUE THREAD

**Issue by testworksau** [ossf/allstar#255]
We'd like to set up a defined branch protection baseline that all repositories must adhere to, for example:

```
optConfig:
  # All repos will use this strategy by default
  optOutStrategy: true
  # Do not allow repos to override this config
  disableRepoOverride: true

requireApproval: true
approvalCount: 1
requireSignedCommits: true

# The global status checks that must pass in order for a merge to be accepted
requireStatusChecks:
  - context: "Security Checks"
```

We'd like to allow teams to configure their own checks on top of this, without having to redefine the mandatory checks nor being able to override the other repo settings. For example, when the below is applied at the repo level, the settings would configure the repo to have three required checks; `Security Checks`, `Lint`, and `Compile`.

```
requireStatusChecks:
  - context: "Lint"
  - context: "Compile"
```

Is this currently possible to achieve via allstar?
