### ISSUE TITLE
Add the ability to allow exceptions to rules per-repository

### ISSUE THREAD

**Issue by coheigea** [ossf/allstar#320]
I think it would be useful to be able to add some exceptions to rules per-repository. Either to override a rule for a given repository, or to exclude the rule from a given file. For example you might want to keep the binary_artifacts rule for a given repository, but allow a regex of files to exclude. 

Maybe something like:
```
exclusions:
 - repo-name:
    exactMatch: exact-file-path
    regex: "**/CustomMatcherTest1.jar" 
```
Another example for the branch_protection case would be to override a particular rule for a given repository:
```
requireApproval: true
exclusions:
  - repo-name:
    - requireApproval: false
```
WDYT? Or is there an existing way to handle these kinds of exceptions?
