### ISSUE TITLE
Allow enabling / disabling on all private / public repos

### ISSUE THREAD

**Issue by jeffmendoza** [ossf/allstar#53]
Right now the opt in/out config must list all repos to opt in or out. It would be good to be able to opt in/out all public or private repos.

**Comment by five510** [comment]
@jeffmendoza 
Hi, I'm trying this issue with https://github.com/ossf/allstar/pull/54. I'm planing to add accessReposConfig property in 
root of allstars.yaml. How do you think this direction?

allstars.yaml
```yaml:allstars.yaml 
optConfig:
  optOutStrategy: false
  optInRepos:
  - repo1
  - repo2
accessReposConfig:
  disablePrivateRepos: true
  disablePublicRepos: true
```
