### ISSUE TITLE
Readme doesn't describe priority order for opt-out features

### ISSUE THREAD

**Issue by Hixie** [ossf/allstar#61]
There are various ways to opt repos in and out, including these:

```
optConfig:
  optOutStrategy: true
  optOutRepos:
  - ...
  optInRepos:
  - ...
  optOutPrivateRepos: true
  optOutPublicRepos: false
```
...and including a per-repo file and an org-wide .allstar repo file.

It is highly unclear from the documentation what will win if there is a conflict ~~(additionally it seems there's an undocumented feature that changes which will win, as mentioned briefly in opt-out.md, which makes this even more unclear)~~. (edit: found the documentation for this feature)

For example, does `optOutPrivateRepos` win vs an explicit `optInRepos`? What if `optOutStrategy` is true, but `optOutPrivateRepos` and `optOutPublicRepos` are also true? What if a repo opts out locally but is listed explicitly in the global .allstar file?
