### ISSUE TITLE
Support the ability to define the repository types for security issues

### ISSUE THREAD

**Issue by coheigea** [ossf/allstar#85]
It would be nice to be able to define the repository types to include for the security issues. For example, we might want a SECURITY.md for all public and internal repos, but not care about whether private repos have it or not.

**Comment by jeffmendoza** [comment]
Hi @coheigea Thanks for the question.
This is possible if you set your `security.yaml` to:
```yaml
optConfig:
  optOutStrategy: true
  optOutPrivateRepos: true
aciton: issue
```
You might also want to opt-out private repos on `branch_protection.yaml` as well, unless you are paying for that feature in GitHub.
